/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/components/Header': RouteRecordInfo<'/admin/components/Header', '/admin/components/Header', Record<never, never>, Record<never, never>>,
    '/admin/layouts/default': RouteRecordInfo<'/admin/layouts/default', '/admin/layouts/default', Record<never, never>, Record<never, never>>,
    '/admin/pages/': RouteRecordInfo<'/admin/pages/', '/admin/pages', Record<never, never>, Record<never, never>>,
    '/admin/pages/auth/login': RouteRecordInfo<'/admin/pages/auth/login', '/admin/pages/auth/login', Record<never, never>, Record<never, never>>,
    '/admin/pages/office/': RouteRecordInfo<'/admin/pages/office/', '/admin/pages/office', Record<never, never>, Record<never, never>>,
    '/admin/pages/office/create/': RouteRecordInfo<'/admin/pages/office/create/', '/admin/pages/office/create', Record<never, never>, Record<never, never>>,
    '/admin/pages/office/edit/': RouteRecordInfo<'/admin/pages/office/edit/', '/admin/pages/office/edit', Record<never, never>, Record<never, never>>,
    '/admin/pages/user/': RouteRecordInfo<'/admin/pages/user/', '/admin/pages/user', Record<never, never>, Record<never, never>>,
    '/admin/pages/user/create/': RouteRecordInfo<'/admin/pages/user/create/', '/admin/pages/user/create', Record<never, never>, Record<never, never>>,
    '/admin/pages/user/edit/': RouteRecordInfo<'/admin/pages/user/edit/', '/admin/pages/user/edit', Record<never, never>, Record<never, never>>,
  }
}
